#!/usr/bin/env zsh

# MacPorts + Homebrew coexistence plugin
#
# Normal shell:
#   - MacPorts is in PATH
#   - Homebrew bin/sbin are NOT in PATH
#   - Homebrew completions remain available through fpath
#   - Homebrew commands selected in the provider database are exposed as Zsh
#     wrappers
#
# Behaviour:
#
#   brew install foo
#       -> isolated Homebrew environment
#       -> newly installed executables automatically become default
#
#   pkg-default foo macports
#       -> removes Brew wrapper and lets MacPorts PATH win
#
#   pkg-default foo brew
#       -> restores Brew wrapper
#
#   brew-shell
#       -> opens full Homebrew environment
#
# Main commands:
#
#   pkg-bootstrap [formula...]
#   pkg-rescan [formula...]
#   pkg-default <command> <brew|macports>
#   pkg-which <command>
#   pkg-list
#   pkg-clean
#   brew-bottle-check <formula...>
#   brew-shell
#

# Load only on Intel macOS when MacPorts is selected and both package managers
# are installed.
if [[ ${DOTFILES_INTEL_PACKAGE_MANAGER:-macports} == macports ]] &&
    [[ $OSTYPE == darwin* && $(uname -m) == x86_64 ]] &&
    [[ -x ${HOMEBREW_BREW:-/usr/local/bin/brew} ]] &&
    [[ -x ${MACPORTS_PREFIX:-/opt/local}/bin/port ]]; then

typeset -g PKGMGR_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}/zsh"
typeset -g PKGMGR_DB="$PKGMGR_STATE_HOME/package-providers.db"
typeset -g PKGMGR_DB_LOCK="$PKGMGR_STATE_HOME/package-providers.lock"
typeset -g MACPORTS_PREFIX="${MACPORTS_PREFIX:-/opt/local}"
typeset -g HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-/usr/local}"
typeset -g HOMEBREW_BREW="${HOMEBREW_BREW:-$HOMEBREW_PREFIX/bin/brew}"

command mkdir -p -- "$PKGMGR_STATE_HOME" || {
    print -u2 -r -- "pkgmng: cannot create state directory: $PKGMGR_STATE_HOME"
    return 1
}
command touch -- "$PKGMGR_DB" || {
    print -u2 -r -- "pkgmng: cannot create provider database: $PKGMGR_DB"
    return 1
}


# ============================================================================
# STATE
# ============================================================================

typeset -gA PKGMGR_GENERATED_WRAPPERS
typeset -g PKGMGR_BREW_MANAGED=true


# ============================================================================
# PATH
# ============================================================================
#
# Homebrew executables are hidden from the normal shell.
#

if [[ -z ${PKGMGR_BREW_SHELL:-} ]]; then

    path=(
        ${path:#$HOMEBREW_PREFIX/bin}
    )

    path=(
        ${path:#$HOMEBREW_PREFIX/sbin}
    )

    path=(
        "$MACPORTS_PREFIX/bin"
        "$MACPORTS_PREFIX/sbin"
        $path
    )

    typeset -gU path PATH
fi


# ============================================================================
# FPATH / COMPLETIONS
# ============================================================================
#
# Important:
#
# Homebrew bin is hidden from PATH, but its Zsh completion definitions remain
# available.
#
# Typical location:
#
#   /usr/local/share/zsh/site-functions
#

if [[ -d "$HOMEBREW_PREFIX/share/zsh/site-functions" ]]; then

    fpath=(
        "$HOMEBREW_PREFIX/share/zsh/site-functions"
        $fpath
    )

fi


if [[ -d "$MACPORTS_PREFIX/share/zsh/site-functions" ]]; then

    fpath=(
        "$MACPORTS_PREFIX/share/zsh/site-functions"
        $fpath
    )

fi

typeset -gU fpath


# ============================================================================
# REAL HOMEBREW
# ============================================================================
#
# Homebrew runs in a subshell using the environment generated by shellenv.
#
# The parent shell remains untouched.
#

_brew_real() {
    [[ -x "$HOMEBREW_BREW" ]] || {
        print -u2 -r -- "Homebrew is not installed at $HOMEBREW_BREW."
        return 127
    }

    (
        eval "$("$HOMEBREW_BREW" shellenv zsh)"
        command "$HOMEBREW_BREW" "$@"
    )
}


# ============================================================================
# HOMEBREW BOTTLE PREFLIGHT
# ============================================================================
#
# Check the artifacts selected by a normal Homebrew install for the requested
# stable formulae and their recursive required/recommended dependencies.
# Nothing is downloaded or installed.
#
# Return values:
#   0  every checked formula selects a bottle
#   1  at least one checked formula selects a source archive
#   2  invalid usage or a Homebrew query error
#

brew-bottle-check() (
    emulate -L zsh
    setopt pipefail

    if (( $# < 1 )); then
        print -u2 -r -- "Usage: brew-bottle-check <formula> [formula ...]"
        return 2
    fi

    [[ -x "$HOMEBREW_BREW" ]] || {
        print -u2 -r -- "ERROR: Homebrew is not installed at $HOMEBREW_BREW."
        return 2
    }

    export HOMEBREW_NO_AUTO_UPDATE=1
    export HOMEBREW_NO_INSTALL_CLEANUP=1
    export HOMEBREW_NO_ENV_HINTS=1

    local -a requested packages source_packages
    local formula dependencies pkg normal_cache source_cache
    local bottle_count=0
    local source_count=0
    local error_count=0

    requested=("$@")

    for formula in "${requested[@]}"; do
        if ! _brew_real info --formula -- "$formula" >/dev/null 2>&1; then
            print -u2 -r -- "ERROR: unable to resolve Homebrew formula: $formula"
            return 2
        fi
    done

    dependencies="$(
        _brew_real deps \
            --formula \
            --full-name \
            --topological \
            --union \
            -- \
            "${requested[@]}" \
            2>/dev/null
    )" || {
        print -u2 -r -- "ERROR: unable to resolve Homebrew dependencies"
        return 2
    }

    packages=("${requested[@]}")
    [[ -z "$dependencies" ]] || packages+=("${(@f)dependencies}")
    typeset -U packages

    printf 'Homebrew: %s\n' "$HOMEBREW_PREFIX"
    printf 'Formulae: %s\n\n' "${requested[*]}"
    printf '%-38s %s\n' "FORMULA" "STATUS"
    printf '%-38s %s\n' "--------------------------------------" "--------"

    for pkg in "${packages[@]}"; do
        normal_cache="$(
            _brew_real --cache --formula -- "$pkg" 2>/dev/null
        )"

        if [[ $? -ne 0 || -z "$normal_cache" ]]; then
            printf '%-38s %s\n' "$pkg" "ERROR"
            (( ++error_count ))
            continue
        fi

        source_cache="$(
            _brew_real --cache \
                --formula \
                --build-from-source \
                -- \
                "$pkg" \
                2>/dev/null
        )"

        if [[ $? -ne 0 || -z "$source_cache" ]]; then
            printf '%-38s %s\n' "$pkg" "ERROR"
            (( ++error_count ))
            continue
        fi

        if [[ "$normal_cache" == "$source_cache" ]]; then
            printf '%-38s %s\n' "$pkg" "SOURCE"
            source_packages+=("$pkg")
            (( ++source_count ))
        else
            printf '%-38s %s\n' "$pkg" "BOTTLE"
            (( ++bottle_count ))
        fi
    done

    print
    printf 'Checked: %d\n' "${#packages[@]}"
    printf 'Bottles: %d\n' "$bottle_count"
    printf 'Source:  %d\n' "$source_count"

    if (( error_count > 0 )); then
        printf 'Errors:  %d\n\n' "$error_count"
        print -r -- "RESULT: CHECK FAILED"
        return 2
    fi

    if (( source_count > 0 )); then
        print
        print -r -- "Would compile:"
        printf '  %s\n' "${source_packages[@]}"
        print
        print -r -- "RESULT: SOURCE BUILD REQUIRED"
        return 1
    fi

    print
    print -r -- "RESULT: BOTTLES ONLY"
    return 0
)


# ============================================================================
# DATABASE
# ============================================================================
#
# Format:
#
#   command        formula        provider
#
# Example:
#
#   jq             jq             brew
#   xz             xz             macports
#   unxz           xz             brew
#

_pkgmgr_db_lock_acquire() {
    local attempts=0

    until command mkdir -- "$PKGMGR_DB_LOCK" 2>/dev/null; do
        (( ++attempts <= 200 )) || {
            print -u2 -r -- "pkgmng: timed out waiting for database lock: $PKGMGR_DB_LOCK"
            return 1
        }
        sleep 0.01
    done
}


_pkgmgr_db_lock_release() {
    command rmdir -- "$PKGMGR_DB_LOCK" 2>/dev/null
}

_pkgmgr_db_set() {
    local cmd="$1"
    local formula="$2"
    local provider="$3"

    local tmp="${PKGMGR_DB}.tmp.$$"
    _pkgmgr_db_lock_acquire || return

    {
        awk -v cmd="$cmd" '
            /^[[:space:]]*#/ || NF == 0 || $1 != cmd { print }
        ' "$PKGMGR_DB" > "$tmp" &&
            printf "%-24s %-24s %s\n" "$cmd" "$formula" "$provider" >> "$tmp" &&
            command mv -- "$tmp" "$PKGMGR_DB"
    } always {
        command rm -f -- "$tmp"
        _pkgmgr_db_lock_release
    }
}


_pkgmgr_db_formula() {
    local cmd="$1"

    awk -v cmd="$cmd" '
        $1 == cmd && $1 !~ /^#/ {
            print $2
            exit
        }
    ' "$PKGMGR_DB"
}


_pkgmgr_db_provider() {
    local cmd="$1"

    awk -v cmd="$cmd" '
        $1 == cmd && $1 !~ /^#/ {
            print $3
            exit
        }
    ' "$PKGMGR_DB"
}


# ============================================================================
# HOMEBREW FORMULA PREFIX
# ============================================================================

_pkgmgr_brew_formula_prefix() {
    local formula="$1"

    _brew_real --prefix "$formula" 2>/dev/null
}


# ============================================================================
# HOMEBREW COMMAND PATH
# ============================================================================

_pkgmgr_brew_path() {
    local formula="$1"
    local cmd="$2"

    local prefix

    prefix="$(
        _pkgmgr_brew_formula_prefix "$formula"
    )" || return 1

    [[ -n "$prefix" ]] || return 1

    if [[ -x "$prefix/bin/$cmd" ]]; then

        print -r -- "$prefix/bin/$cmd"
        return 0

    fi


    if [[ -x "$prefix/sbin/$cmd" ]]; then

        print -r -- "$prefix/sbin/$cmd"
        return 0

    fi


    return 1
}


# ============================================================================
# MACPORTS COMMAND PATH
# ============================================================================

_pkgmgr_macports_path() {
    local cmd="$1"

    if [[ -x "$MACPORTS_PREFIX/bin/$cmd" ]]; then

        print -r -- "$MACPORTS_PREFIX/bin/$cmd"
        return 0

    fi


    if [[ -x "$MACPORTS_PREFIX/sbin/$cmd" ]]; then

        print -r -- "$MACPORTS_PREFIX/sbin/$cmd"
        return 0

    fi


    return 1
}


# ============================================================================
# FORMULA EXECUTABLE DISCOVERY
# ============================================================================

_brew_formula_commands() {
    local formula="$1"
    local prefix
    local file

    prefix="$(
        _pkgmgr_brew_formula_prefix "$formula"
    )" || return 1

    [[ -d "$prefix" ]] || return 1

    for file in \
        "$prefix"/bin/*(N) \
        "$prefix"/sbin/*(N)
    do

        [[ -x "$file" ]] || continue
        [[ -d "$file" ]] && continue

        basename "$file"

    done | sort -u
}


# ============================================================================
# GENERATED WRAPPERS
# ============================================================================

_pkgmgr_clear_wrappers() {
    local cmd

    for cmd in ${(k)PKGMGR_GENERATED_WRAPPERS}; do

        unfunction "$cmd" 2>/dev/null

    done

    PKGMGR_GENERATED_WRAPPERS=()
}


_pkgmgr_define_wrapper() {
    local cmd="$1"
    local target="$2"

    [[ -x "$target" ]] || return 1

    local command_kind="$(whence -w -- "$cmd" 2>/dev/null)"
    if [[ "$command_kind" == *': alias' ||
          "$command_kind" == *': builtin' ||
          "$command_kind" == *': reserved' ]]; then
        print -u2 -r -- "pkgmng: refusing to replace shell command '$cmd'."
        return 1
    fi
    if [[ "$command_kind" == *': function' &&
          " ${(k)PKGMGR_GENERATED_WRAPPERS} " != *" $cmd "* ]]; then
        print -u2 -r -- "pkgmng: refusing to replace function '$cmd'."
        return 1
    fi

    # Preserve any completion already associated with this command.

    local completion=""

    if (( ${+_comps} )); then
        completion="${_comps[$cmd]-}"
    fi

    functions[$cmd]="_pkgmgr_brew_exec ${(q)target} \"\$@\""

    PKGMGR_GENERATED_WRAPPERS[$cmd]=1

    # Restore the completion mapping if compsys is already initialized.

    if [[ -n "$completion" ]] && (( $+functions[compdef] )); then
        compdef "$completion" "$cmd"
    fi
}


_pkgmgr_brew_exec() {
    local target="$1"
    shift

    (
        eval "$("$HOMEBREW_BREW" shellenv zsh)" || return
        command "$target" "$@"
    )
}


# ============================================================================
# LOAD WRAPPERS
# ============================================================================

_pkgmgr_load_wrappers() {
    local cmd
    local formula
    local provider
    local target

    while read -r cmd formula provider; do

        [[ -z "$cmd" ]] && continue
        [[ "$cmd" == \#* ]] && continue

        case "$provider" in

            brew)

                target="$(
                    _pkgmgr_brew_path \
                        "$formula" \
                        "$cmd"
                )"

                [[ -n "$target" ]] || continue

                _pkgmgr_define_wrapper \
                    "$cmd" \
                    "$target"
                ;;


            macports)

                # No wrapper required.
                #
                # MacPorts is already before system paths in PATH.

                ;;

        esac

    done < "$PKGMGR_DB"
}


_pkgmgr_reload() {
    _pkgmgr_clear_wrappers
    _pkgmgr_load_wrappers

    rehash
}


# ============================================================================
# HOMEBREW COMPLETION
# ============================================================================
#
# Call this after compinit if required.
#

_pkgmgr_setup_completions() {

    (( $+functions[compdef] )) || return 0

    # Homebrew itself.

    if (( $+functions[_brew] )); then
        compdef _brew brew
    fi

    compdef _brew_bottle_check_completion brew-bottle-check

    # Reassociate known completion functions with wrapper commands.
    #
    # In most cases this is unnecessary because completion is keyed by command
    # name, not by executable path. It is kept here to make wrapper reloads
    # predictable.

    local cmd
    local formula
    local provider
    local completion

    while read -r cmd formula provider; do

        [[ -z "$cmd" ]] && continue
        [[ "$cmd" == \#* ]] && continue

        [[ "$provider" != "brew" ]] && continue

        completion="${_comps[$cmd]-}"

        [[ -n "$completion" ]] || continue

        compdef "$completion" "$cmd"

    done < "$PKGMGR_DB"
}


_brew_bottle_check_completion() {
    if (( $+functions[__brew_formulae] )); then
        __brew_formulae
        return
    fi

    local -a formulae
    formulae=("${(@f)$(HOMEBREW_COMPLETION=1 brew formulae 2>/dev/null)}")
    (( ${#formulae} )) || {
        _message 'Homebrew formula'
        return
    }
    _describe -t formulae 'Homebrew formulae' formulae
}


# ============================================================================
# REGISTER FORMULA
# ============================================================================
#
# Every executable from a newly installed formula automatically becomes Brew
# default.
#

_brew_register_formula() {
    local formula="$1"
    local cmd
    local target
    local provider

    print
    print "Registering Homebrew formula: $formula"

    while IFS= read -r cmd; do

        [[ -z "$cmd" ]] && continue

        target="$(
            _pkgmgr_brew_path \
                "$formula" \
                "$cmd"
        )"

        [[ -n "$target" ]] || continue

        provider="$(_pkgmgr_db_provider "$cmd")"
        [[ "$provider" == macports ]] || provider=brew

        _pkgmgr_db_set \
            "$cmd" \
            "$formula" \
            "$provider"

        print "  $cmd -> $provider"

    done < <(
        _brew_formula_commands "$formula"
    )
}


# ============================================================================
# INSTALLED HOMEBREW FORMULAE
# ============================================================================

_brew_installed_formulae() {
    _brew_real list --formula 2>/dev/null
}


# ============================================================================
# RESCAN
# ============================================================================

pkg-rescan() {
    local formula

    if (( $# )); then

        for formula in "$@"; do

            _brew_register_formula "$formula"

        done

    else

        while IFS= read -r formula; do

            [[ -z "$formula" ]] && continue

            _brew_register_formula "$formula"

        done < <(
            _brew_installed_formulae
        )

    fi

    _pkgmgr_reload
    _pkgmgr_setup_completions
}


# ============================================================================
# BOOTSTRAP EXISTING HOMEBREW
# ============================================================================

pkg-bootstrap() {
    print
    print "Importing existing Homebrew installation..."
    print

    pkg-rescan "$@"

    print
    print "Bootstrap complete."
}


# ============================================================================
# CHANGE DEFAULT PROVIDER
# ============================================================================

pkg-default() {
    if (( $# != 2 )); then

        print "usage:"
        print "  pkg-default <command> brew"
        print "  pkg-default <command> macports"

        return 2
    fi

    local cmd="$1"
    local provider="$2"

    local formula

    formula="$(
        _pkgmgr_db_formula "$cmd"
    )"

    if [[ -z "$formula" ]]; then

        print "Command '$cmd' is not managed."
        return 1

    fi


    case "$provider" in

        brew)

            if ! _pkgmgr_brew_path \
                    "$formula" \
                    "$cmd" \
                    >/dev/null
            then

                print "$cmd is not provided by Homebrew formula '$formula'."
                return 1

            fi

            ;;


        macports)

            if ! _pkgmgr_macports_path \
                    "$cmd" \
                    >/dev/null
            then

                print "$cmd is not provided by MacPorts."
                return 1

            fi

            ;;


        *)

            print "Invalid provider: $provider"
            return 2

            ;;

    esac


    _pkgmgr_db_set \
        "$cmd" \
        "$formula" \
        "$provider"

    _pkgmgr_reload
    _pkgmgr_setup_completions

    print "$cmd -> $provider"
}


# ============================================================================
# INSPECT COMMAND
# ============================================================================

pkg-which() {
    if (( $# != 1 )); then

        print "usage: pkg-which <command>"
        return 2

    fi

    local cmd="$1"

    local formula
    local provider

    local brew_path
    local ports_path

    formula="$(
        _pkgmgr_db_formula "$cmd"
    )"

    provider="$(
        _pkgmgr_db_provider "$cmd"
    )"


    if [[ -n "$formula" ]]; then

        brew_path="$(
            _pkgmgr_brew_path \
                "$formula" \
                "$cmd"
        )"

    fi


    ports_path="$(
        _pkgmgr_macports_path "$cmd"
    )"


    print
    print "$cmd"
    print "--------------------------------------------------"

    [[ -n "$brew_path" ]] &&
        print "Homebrew:  $brew_path"

    [[ -n "$ports_path" ]] &&
        print "MacPorts:  $ports_path"

    [[ -n "$formula" ]] &&
        print "Formula:   $formula"

    print

    if [[ -n "$provider" ]]; then

        print "Default:   $provider"

    else

        print "Default:   unmanaged"

    fi

    print

    whence -v "$cmd"

    if (( ${+_comps} )); then

        local completion="${_comps[$cmd]-}"

        [[ -n "$completion" ]] &&
            print "Completion: $completion"

    fi
}


# ============================================================================
# LIST DATABASE
# ============================================================================

pkg-list() {

    printf "%-24s %-24s %-12s\n" \
        "COMMAND" \
        "FORMULA" \
        "DEFAULT"

    printf "%-24s %-24s %-12s\n" \
        "------------------------" \
        "------------------------" \
        "------------"

    awk '
        NF >= 3 && $1 !~ /^#/ {
            printf "%-24s %-24s %-12s\n", $1, $2, $3
        }
    ' "$PKGMGR_DB"
}


# ============================================================================
# CLEAN STALE ENTRIES
# ============================================================================

pkg-clean() {
    local cmd
    local formula
    local provider

    local tmp="${PKGMGR_DB}.tmp.$$"

    _pkgmgr_db_lock_acquire || return

    {

    typeset -A installed

    local f

    while IFS= read -r f; do

        [[ -n "$f" ]] &&
            installed[$f]=1

    done < <(
        _brew_installed_formulae
    )


    : > "$tmp"


    while read -r cmd formula provider; do

        [[ -z "$cmd" ]] && continue
        [[ "$cmd" == \#* ]] && continue


        if [[ "$provider" == macports ]] && _pkgmgr_macports_path "$cmd" >/dev/null; then

            printf "%-24s %-24s %s\n" \
                "$cmd" \
                "$formula" \
                "$provider" \
                >> "$tmp"

        elif [[ "$provider" == brew && -n "${installed[$formula]}" ]] &&
             _pkgmgr_brew_path "$formula" "$cmd" >/dev/null; then

            printf "%-24s %-24s %s\n" \
                "$cmd" \
                "$formula" \
                "$provider" \
                >> "$tmp"

        else

            print "Removing stale entry:"
            print "  $cmd ($formula)"

        fi

    done < "$PKGMGR_DB"


    command mv -- "$tmp" "$PKGMGR_DB"

    } always {
        command rm -f -- "$tmp"
        _pkgmgr_db_lock_release
    }

    _pkgmgr_reload
    _pkgmgr_setup_completions
}


# ============================================================================
# BREW SHELL
# ============================================================================

brew-shell() {
    [[ -x "$HOMEBREW_BREW" ]] || {
        print -u2 -r -- "Homebrew is not installed at $HOMEBREW_BREW."
        return 127
    }

    (
        eval "$("$HOMEBREW_BREW" shellenv zsh)"

        export PKGMGR_BREW_SHELL=1

        print
        print "Homebrew shell"
        print "--------------------------------------------------"
        print "Prefix: $HOMEBREW_PREFIX"
        print
        print "Full Homebrew environment enabled."
        print "Type 'exit' to return."
        print

        exec "${SHELL:-/bin/zsh}" -i
    )
}


# ============================================================================
# BREW WRAPPER
# ============================================================================

brew() {

    [[ -x "$HOMEBREW_BREW" ]] || {
        print -u2 -r -- "Homebrew is not installed at $HOMEBREW_BREW."
        return 127
    }

    # Preserve the Homebrew 6 completion fallback owned by the fzf layer
    # without allowing that layer to replace this execution wrapper.
    if [[ ${HOMEBREW_COMPLETION:-} == 1 &&
          ( ${1:-} == formulae || ${1:-} == casks ) ]]; then
        local kind=${1%?}
        local api_dir=${HOMEBREW_CACHE:-$HOME/Library/Caches/Homebrew}/api
        local names_file=$api_dir/${kind}_names.txt
        [[ -s $names_file ]] || names_file=$api_dir/${kind}_names.before.txt
        if [[ -s $names_file ]]; then
            command cat -- "$names_file"
            return
        fi
    fi

    # Already inside brew-shell.

    if [[ -n ${PKGMGR_BREW_SHELL:-} ]]; then

        command "$HOMEBREW_BREW" "$@"
        return $?

    fi


    if (( $# == 0 )); then

        _brew_real
        return $?

    fi


    local subcommand="$1"


    case "$subcommand" in

        install)

            typeset -A before

            local formula


            # Snapshot installed formulae before installation.

            while IFS= read -r formula; do

                [[ -n "$formula" ]] &&
                    before[$formula]=1

            done < <(
                _brew_installed_formulae
            )


            _brew_real "$@"

            local rc=$?

            (( rc != 0 )) && return $rc


            # Detect every newly installed formula, including dependencies.

            while IFS= read -r formula; do

                [[ -z "$formula" ]] && continue

                if [[ -z "${before[$formula]}" ]]; then

                    _brew_register_formula "$formula"

                fi

            done < <(
                _brew_installed_formulae
            )


            _pkgmgr_reload
            _pkgmgr_setup_completions

            return 0
            ;;


        upgrade)

            _brew_real "$@"

            local rc=$?

            (( rc != 0 )) && return $rc


            # A new version may introduce new executable names.

            pkg-rescan

            pkg-clean

            return 0
            ;;


        uninstall|remove|rm)

            _brew_real "$@"

            local rc=$?

            (( rc != 0 )) && return $rc

            pkg-clean

            return 0
            ;;


        *)

            _brew_real "$@"
            return $?

            ;;

    esac
}


# ============================================================================
# INITIAL LOAD
# ============================================================================

if [[ -z ${PKGMGR_BREW_SHELL:-} ]]; then

    _pkgmgr_load_wrappers

fi

fi
